package mybatis.mapper;

import java.util.List;
import mybatis.persistence.TbDate;
import mybatis.persistence.TbDateExample;
import org.apache.ibatis.annotations.Param;

public interface TbDateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_DATE
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int countByExample(TbDateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_DATE
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int deleteByExample(TbDateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_DATE
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int insert(TbDate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_DATE
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int insertSelective(TbDate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_DATE
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	List<TbDate> selectByExample(TbDateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_DATE
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TbDate record, @Param("example") TbDateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_DATE
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int updateByExample(@Param("record") TbDate record, @Param("example") TbDateExample example);
}