package mybatis.mapper;

import java.util.List;
import mybatis.persistence.TbString;
import mybatis.persistence.TbStringExample;
import mybatis.persistence.TbStringWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface TbStringMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int countByExample(TbStringExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int deleteByExample(TbStringExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int insert(TbStringWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int insertSelective(TbStringWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	List<TbStringWithBLOBs> selectByExampleWithBLOBs(TbStringExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	List<TbString> selectByExample(TbStringExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TbStringWithBLOBs record, @Param("example") TbStringExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") TbStringWithBLOBs record, @Param("example") TbStringExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	int updateByExample(@Param("record") TbString record, @Param("example") TbStringExample example);
}