package mybatis.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbDate implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_DATE.d_year_4
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private String dYear4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_DATE.d_date
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Date dDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_DATE.d_time
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Date dTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_DATE.d_datetime
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Date dDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_DATE.d_timestamp
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Date dTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_DATE
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_DATE.d_year_4
	 * @return  the value of TB_DATE.d_year_4
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public String getdYear4() {
		return dYear4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_DATE.d_year_4
	 * @param dYear4  the value for TB_DATE.d_year_4
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setdYear4(String dYear4) {
		this.dYear4 = dYear4 == null ? null : dYear4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_DATE.d_date
	 * @return  the value of TB_DATE.d_date
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Date getdDate() {
		return dDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_DATE.d_date
	 * @param dDate  the value for TB_DATE.d_date
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setdDate(Date dDate) {
		this.dDate = dDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_DATE.d_time
	 * @return  the value of TB_DATE.d_time
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Date getdTime() {
		return dTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_DATE.d_time
	 * @param dTime  the value for TB_DATE.d_time
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setdTime(Date dTime) {
		this.dTime = dTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_DATE.d_datetime
	 * @return  the value of TB_DATE.d_datetime
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Date getdDatetime() {
		return dDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_DATE.d_datetime
	 * @param dDatetime  the value for TB_DATE.d_datetime
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setdDatetime(Date dDatetime) {
		this.dDatetime = dDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_DATE.d_timestamp
	 * @return  the value of TB_DATE.d_timestamp
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Date getdTimestamp() {
		return dTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_DATE.d_timestamp
	 * @param dTimestamp  the value for TB_DATE.d_timestamp
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setdTimestamp(Date dTimestamp) {
		this.dTimestamp = dTimestamp;
	}
}