package mybatis.persistence;

import java.io.Serializable;
import java.math.BigDecimal;

public class TbNumber implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_NUMBER.n_tiny
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Byte nTiny;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_NUMBER.n_small
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Short nSmall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_NUMBER.n_mediun
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Integer nMediun;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_NUMBER.n_int
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Integer nInt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_NUMBER.n_big
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Long nBig;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_NUMBER.n_float
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Float nFloat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_NUMBER.n_doble
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private Double nDoble;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_NUMBER.n_decimal
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private BigDecimal nDecimal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_NUMBER.n_numeric
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private BigDecimal nNumeric;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_NUMBER
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_NUMBER.n_tiny
	 * @return  the value of TB_NUMBER.n_tiny
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Byte getnTiny() {
		return nTiny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_NUMBER.n_tiny
	 * @param nTiny  the value for TB_NUMBER.n_tiny
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setnTiny(Byte nTiny) {
		this.nTiny = nTiny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_NUMBER.n_small
	 * @return  the value of TB_NUMBER.n_small
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Short getnSmall() {
		return nSmall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_NUMBER.n_small
	 * @param nSmall  the value for TB_NUMBER.n_small
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setnSmall(Short nSmall) {
		this.nSmall = nSmall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_NUMBER.n_mediun
	 * @return  the value of TB_NUMBER.n_mediun
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Integer getnMediun() {
		return nMediun;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_NUMBER.n_mediun
	 * @param nMediun  the value for TB_NUMBER.n_mediun
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setnMediun(Integer nMediun) {
		this.nMediun = nMediun;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_NUMBER.n_int
	 * @return  the value of TB_NUMBER.n_int
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Integer getnInt() {
		return nInt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_NUMBER.n_int
	 * @param nInt  the value for TB_NUMBER.n_int
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setnInt(Integer nInt) {
		this.nInt = nInt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_NUMBER.n_big
	 * @return  the value of TB_NUMBER.n_big
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Long getnBig() {
		return nBig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_NUMBER.n_big
	 * @param nBig  the value for TB_NUMBER.n_big
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setnBig(Long nBig) {
		this.nBig = nBig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_NUMBER.n_float
	 * @return  the value of TB_NUMBER.n_float
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Float getnFloat() {
		return nFloat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_NUMBER.n_float
	 * @param nFloat  the value for TB_NUMBER.n_float
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setnFloat(Float nFloat) {
		this.nFloat = nFloat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_NUMBER.n_doble
	 * @return  the value of TB_NUMBER.n_doble
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Double getnDoble() {
		return nDoble;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_NUMBER.n_doble
	 * @param nDoble  the value for TB_NUMBER.n_doble
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setnDoble(Double nDoble) {
		this.nDoble = nDoble;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_NUMBER.n_decimal
	 * @return  the value of TB_NUMBER.n_decimal
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public BigDecimal getnDecimal() {
		return nDecimal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_NUMBER.n_decimal
	 * @param nDecimal  the value for TB_NUMBER.n_decimal
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setnDecimal(BigDecimal nDecimal) {
		this.nDecimal = nDecimal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_NUMBER.n_numeric
	 * @return  the value of TB_NUMBER.n_numeric
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public BigDecimal getnNumeric() {
		return nNumeric;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_NUMBER.n_numeric
	 * @param nNumeric  the value for TB_NUMBER.n_numeric
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setnNumeric(BigDecimal nNumeric) {
		this.nNumeric = nNumeric;
	}
}