package mybatis.persistence;

import java.util.ArrayList;
import java.util.List;

public class TbStringExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public TbStringExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSNbCharIsNull() {
			addCriterion("s_nb_char is null");
			return (Criteria) this;
		}

		public Criteria andSNbCharIsNotNull() {
			addCriterion("s_nb_char is not null");
			return (Criteria) this;
		}

		public Criteria andSNbCharEqualTo(String value) {
			addCriterion("s_nb_char =", value, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharNotEqualTo(String value) {
			addCriterion("s_nb_char <>", value, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharGreaterThan(String value) {
			addCriterion("s_nb_char >", value, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharGreaterThanOrEqualTo(String value) {
			addCriterion("s_nb_char >=", value, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharLessThan(String value) {
			addCriterion("s_nb_char <", value, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharLessThanOrEqualTo(String value) {
			addCriterion("s_nb_char <=", value, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharLike(String value) {
			addCriterion("s_nb_char like", value, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharNotLike(String value) {
			addCriterion("s_nb_char not like", value, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharIn(List<String> values) {
			addCriterion("s_nb_char in", values, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharNotIn(List<String> values) {
			addCriterion("s_nb_char not in", values, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharBetween(String value1, String value2) {
			addCriterion("s_nb_char between", value1, value2, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbCharNotBetween(String value1, String value2) {
			addCriterion("s_nb_char not between", value1, value2, "sNbChar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharIsNull() {
			addCriterion("s_nb_varchar is null");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharIsNotNull() {
			addCriterion("s_nb_varchar is not null");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharEqualTo(String value) {
			addCriterion("s_nb_varchar =", value, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharNotEqualTo(String value) {
			addCriterion("s_nb_varchar <>", value, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharGreaterThan(String value) {
			addCriterion("s_nb_varchar >", value, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharGreaterThanOrEqualTo(String value) {
			addCriterion("s_nb_varchar >=", value, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharLessThan(String value) {
			addCriterion("s_nb_varchar <", value, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharLessThanOrEqualTo(String value) {
			addCriterion("s_nb_varchar <=", value, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharLike(String value) {
			addCriterion("s_nb_varchar like", value, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharNotLike(String value) {
			addCriterion("s_nb_varchar not like", value, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharIn(List<String> values) {
			addCriterion("s_nb_varchar in", values, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharNotIn(List<String> values) {
			addCriterion("s_nb_varchar not in", values, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharBetween(String value1, String value2) {
			addCriterion("s_nb_varchar between", value1, value2, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSNbVarcharNotBetween(String value1, String value2) {
			addCriterion("s_nb_varchar not between", value1, value2, "sNbVarchar");
			return (Criteria) this;
		}

		public Criteria andSBCharIsNull() {
			addCriterion("s_b_char is null");
			return (Criteria) this;
		}

		public Criteria andSBCharIsNotNull() {
			addCriterion("s_b_char is not null");
			return (Criteria) this;
		}

		public Criteria andSBCharEqualTo(String value) {
			addCriterion("s_b_char =", value, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharNotEqualTo(String value) {
			addCriterion("s_b_char <>", value, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharGreaterThan(String value) {
			addCriterion("s_b_char >", value, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharGreaterThanOrEqualTo(String value) {
			addCriterion("s_b_char >=", value, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharLessThan(String value) {
			addCriterion("s_b_char <", value, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharLessThanOrEqualTo(String value) {
			addCriterion("s_b_char <=", value, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharLike(String value) {
			addCriterion("s_b_char like", value, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharNotLike(String value) {
			addCriterion("s_b_char not like", value, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharIn(List<String> values) {
			addCriterion("s_b_char in", values, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharNotIn(List<String> values) {
			addCriterion("s_b_char not in", values, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharBetween(String value1, String value2) {
			addCriterion("s_b_char between", value1, value2, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBCharNotBetween(String value1, String value2) {
			addCriterion("s_b_char not between", value1, value2, "sBChar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharIsNull() {
			addCriterion("s_b_varchar is null");
			return (Criteria) this;
		}

		public Criteria andSBVarcharIsNotNull() {
			addCriterion("s_b_varchar is not null");
			return (Criteria) this;
		}

		public Criteria andSBVarcharEqualTo(String value) {
			addCriterion("s_b_varchar =", value, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharNotEqualTo(String value) {
			addCriterion("s_b_varchar <>", value, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharGreaterThan(String value) {
			addCriterion("s_b_varchar >", value, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharGreaterThanOrEqualTo(String value) {
			addCriterion("s_b_varchar >=", value, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharLessThan(String value) {
			addCriterion("s_b_varchar <", value, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharLessThanOrEqualTo(String value) {
			addCriterion("s_b_varchar <=", value, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharLike(String value) {
			addCriterion("s_b_varchar like", value, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharNotLike(String value) {
			addCriterion("s_b_varchar not like", value, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharIn(List<String> values) {
			addCriterion("s_b_varchar in", values, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharNotIn(List<String> values) {
			addCriterion("s_b_varchar not in", values, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharBetween(String value1, String value2) {
			addCriterion("s_b_varchar between", value1, value2, "sBVarchar");
			return (Criteria) this;
		}

		public Criteria andSBVarcharNotBetween(String value1, String value2) {
			addCriterion("s_b_varchar not between", value1, value2, "sBVarchar");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_STRING
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 14 09:55:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}