package mybatis.persistence;

import java.io.Serializable;

public class TbString implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_STRING.s_nb_char
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private String sNbChar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_STRING.s_nb_varchar
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private String sNbVarchar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_STRING.s_b_char
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private String sBChar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_STRING.s_b_varchar
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private String sBVarchar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_STRING.s_nb_char
	 * @return  the value of TB_STRING.s_nb_char
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public String getsNbChar() {
		return sNbChar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_STRING.s_nb_char
	 * @param sNbChar  the value for TB_STRING.s_nb_char
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setsNbChar(String sNbChar) {
		this.sNbChar = sNbChar == null ? null : sNbChar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_STRING.s_nb_varchar
	 * @return  the value of TB_STRING.s_nb_varchar
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public String getsNbVarchar() {
		return sNbVarchar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_STRING.s_nb_varchar
	 * @param sNbVarchar  the value for TB_STRING.s_nb_varchar
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setsNbVarchar(String sNbVarchar) {
		this.sNbVarchar = sNbVarchar == null ? null : sNbVarchar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_STRING.s_b_char
	 * @return  the value of TB_STRING.s_b_char
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public String getsBChar() {
		return sBChar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_STRING.s_b_char
	 * @param sBChar  the value for TB_STRING.s_b_char
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setsBChar(String sBChar) {
		this.sBChar = sBChar == null ? null : sBChar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_STRING.s_b_varchar
	 * @return  the value of TB_STRING.s_b_varchar
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public String getsBVarchar() {
		return sBVarchar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_STRING.s_b_varchar
	 * @param sBVarchar  the value for TB_STRING.s_b_varchar
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setsBVarchar(String sBVarchar) {
		this.sBVarchar = sBVarchar == null ? null : sBVarchar.trim();
	}
}