package mybatis.persistence;

import java.io.Serializable;

public class TbStringWithBLOBs extends TbString implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_STRING.s_nb_binary
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private byte[] sNbBinary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_STRING.s_b_varbinary
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private byte[] sBVarbinary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_STRING
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_STRING.s_nb_binary
	 * @return  the value of TB_STRING.s_nb_binary
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public byte[] getsNbBinary() {
		return sNbBinary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_STRING.s_nb_binary
	 * @param sNbBinary  the value for TB_STRING.s_nb_binary
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setsNbBinary(byte[] sNbBinary) {
		this.sNbBinary = sNbBinary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_STRING.s_b_varbinary
	 * @return  the value of TB_STRING.s_b_varbinary
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public byte[] getsBVarbinary() {
		return sBVarbinary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_STRING.s_b_varbinary
	 * @param sBVarbinary  the value for TB_STRING.s_b_varbinary
	 * @mbggenerated  Fri Dec 14 11:40:48 CST 2018
	 */
	public void setsBVarbinary(byte[] sBVarbinary) {
		this.sBVarbinary = sBVarbinary;
	}
}